### ISSUE TITLE
I am getting error with this package in playground, can not i use this here?

### ISSUE THREAD

**Issue by fromancient** [jawa-the-hutt/nativescript-vue-shadow#3]
Error: com.tns.NativeScriptException: Failed to find module: "nativescript-vue-shadow", relative to: app/tns_modules/
com.tns.Module.resolvePathHelper(Module.java:151)
com.tns.Module.resolvePath(Module.java:56)
com.tns.Runtime.runModule(Native Method)
com.tns.Runtime.runModule(Runtime.java:662)
com.tns.Runtime.run(Runtime.java:654)
com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
android.app.ActivityThread.handleBindApplication(ActivityThread.java:4995)
android.app.ActivityThread.access$1800(ActivityThread.java:170)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1555)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loop(Looper.java:179)
android.app.ActivityThread.main(ActivityThread.java:5769)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
at com.tns.Runtime.runModule(Native Method)
at com.tns.Runtime.runModule(Runtime.java:662)
at com.tns.Runtime.run(Runtime.java:654)
at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4995)
at android.app.ActivityThread.access$1800(ActivityThread.java:170)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1555)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:179)
at android.app.ActivityThread.main(ActivityThread.java:5769)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
[OPPO A57]: com.tns.NativeScriptException: Error calling module function
Error: com.tns.NativeScriptException: Failed to find module: "nativescript-vue-shadow", relative to: app/tns_modules/
com.tns.Module.resolvePathHelper(Module.java:151)
com.tns.Module.resolvePath(Module.java:56)
com.tns.Runtime.runModule(Native Method)
com.tns.Runtime.runModule(Runtime.java:662)
com.tns.Runtime.run(Runtime.java:654)
com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
android.app.ActivityThread.handleBindApplication(ActivityThread.java:4995)
android.app.ActivityThread.access$1800(ActivityThread.java:170)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1555)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loop(Looper.java:179)
android.app.ActivityThread.main(ActivityThread.java:5769)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
File: (<unknown>:1:265)

StackTrace:
require(:1:266)
at (file:///data/data/org.nativescript.preview/files/app/app.js:11:30)
at require(:1:266)

Error: com.tns.NativeScriptException: Failed to find module: "nativescript-vue-shadow", relative to: app/tns_modules/
com.tns.Module.resolvePathHelper(Module.java:151)
com.tns.Module.resolvePath(Module.java:56)
com.tns.Runtime.runModule(Native Method)
com.tns.Runtime.runModule(Runtime.java:662)
com.tns.Runtime.run(Runtime.java:654)
com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
android.app.ActivityThread.handleBindApplication(ActivityThread.java:4995)
android.app.ActivityThread.access$1800(ActivityThread.java:170)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1555)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loop(Looper.java:179)
android.app.ActivityThread.main(ActivityThread.java:5769)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
at com.tns.Runtime.runModule(Native Method)
at com.tns.Runtime.runModule(Runtime.java:662)
at com.tns.Runtime.run(Runtime.java:654)
at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4995)
at android.app.ActivityThread.access$1800(ActivityThread.java:170)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1555)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:179)
at android.app.ActivityThread.main(ActivityThread.java:5769)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)

**Comment by Upd4ting** [comment]
The playground has preinstalled plugins but not all of them. They wont install all the plugins coming from the internet. 
So you can't use it there no.
